version: '3.1'

services:

  mongo:
    image: mongo:6.0.8
    restart: always
    # container_name: mongo-server
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./.mongo-data:/data/db:rw

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  bloglist-backend:
    entrypoint: ["npm", "run", "dev"]
    image: test-node
    restart: always
    ports:
      - 3001:3001
    environment:
      MONGODB_UN: root
      MONGODB_PW: example
      DATABASE_NAME: testBloglistApp
      TEST_DATABASE_NAME: testBloglistApp
      JWT_SECRET_SIGNATURE: IAMSECRETLY
      PORT: 3001
      MONGO_CLUSTER_URL: "mongo:27017"
      MONGODB_URL: mongodb://root:example@mongo:27017/
